[package]
name = "pond-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pond-core = { workspace = true }
pond-api = { workspace = true }
pond-infra = { workspace = true }
pond-adapters-llamafile = { path = "../../crates/pond-adapters-llamafile" }
pond-adapters-qwen-tts  = { workspace = true }
pond-adapters-ollama = { path = "../../crates/pond-adapters-ollama" }
pond-adapters-whisper = { path = "../../crates/pond-adapters-whisper" }
pond-adapters-piper = { path = "../../crates/pond-adapters-piper" }
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
serde = { workspace = true }
serde_json = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
hostname = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
webbrowser = { workspace = true }
zip = { workspace = true }
flate2 = "1"
tar = "0.4"

[dev-dependencies]
wiremock = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
