[package]
name = "pond-server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pond-core = { workspace = true }
pond-api = { workspace = true }
pond-infra = { workspace = true }
pond-adapters-llamafile = { path = "../../crates/pond-adapters-llamafile" }
pond-adapters-whisper = { path = "../../crates/pond-adapters-whisper" }
anyhow = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls"] }
axum = { workspace = true }
clap = { workspace = true }
dirs = { workspace = true }
hostname = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
sqlx = { workspace = true }
webbrowser = { workspace = true }
