[package]
name = "pond-infra"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
pond-core = { workspace = true }
anyhow = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
async-trait = { workspace = true }
hostname = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
