use crate::giap_server::GiapMcpServer;
use pond_adapters_weather::WeatherProvider;
use pond_core::ports::device_registry::DeviceRegistry;
use pond_core::ports::memory_repository::MemoryRepository;
use pond_core::ports::recipe::AgentRecipeRepository;
use pond_core::ports::scheduler::SchedulerPort;
use pond_core::ports::settings::SettingsRepository;
use pond_core::ports::skill::UserSkillRepository;
use pond_core::ports::tool_caller::ToolCaller;
use rmcp::ServiceExt;
use std::sync::{Arc, OnceLock};
use tokio::io::DuplexStream;

pub struct GiapServiceHandles {
    pub weather: Option<Arc<dyn WeatherProvider>>,
    pub device_registry: Arc<dyn DeviceRegistry + Send + Sync>,
    pub scheduler: Option<Arc<dyn SchedulerPort>>,
    pub settings_repo: Arc<dyn SettingsRepository + Send + Sync>,
    pub memory_repo: Arc<dyn MemoryRepository + Send + Sync>,
    pub skill_repo: Arc<dyn UserSkillRepository + Send + Sync>,
    pub recipe_repo: Arc<dyn AgentRecipeRepository + Send + Sync>,
    /// Shared HTTP client for tools that fetch external data (Wikipedia, etc.).
    pub http_client: reqwest::Client,
    /// Tool-calling specialist model. When `Some`, empty tool arguments are
    /// re-generated by this small model before the tool executes.
    pub tool_caller: Option<Arc<dyn ToolCaller>>,
    /// The most recent user message, updated before each agent turn.
    /// Used as fallback when a tool is called with empty parameters
    /// (common with small local models that struggle with tool-call schemas).
    pub last_user_message: tokio::sync::RwLock<String>,
    /// The entity/topic from the last successful tool lookup (e.g. "John Cena").
    /// Used to resolve pronoun-heavy follow-up queries like "how old is he?"
    /// into "how old is John Cena?" before sending to Wikipedia.
    pub last_tool_topic: tokio::sync::RwLock<String>,
}

static GIAP_SERVICES: OnceLock<Arc<GiapServiceHandles>> = OnceLock::new();

pub fn init_giap_services(services: Arc<GiapServiceHandles>) {
    let _ = GIAP_SERVICES.set(services);
}

/// Update the last user message so tools can use it as a fallback when the
/// model calls a tool with empty parameters.
pub async fn set_last_user_message(msg: &str) {
    if let Some(handles) = GIAP_SERVICES.get() {
        *handles.last_user_message.write().await = msg.to_string();
    }
}

/// Check whether a query is pronoun-heavy and lacks a clear entity.
///
/// Returns `true` for queries like "how old is he?", "where was she born?",
/// "what did they do?" — follow-ups that reference a previous topic without
/// naming it.
fn is_pronoun_query(query: &str) -> bool {
    let lower = query.to_lowercase();
    let pronouns = [
        "he", "she", "they", "him", "her", "them", "his", "hers", "their", "it", "its",
    ];
    let has_pronoun = pronouns.iter().any(|p| {
        // Match whole words: " he ", " he?", starts with "he ", etc.
        lower.split(|c: char| !c.is_alphanumeric()).any(|w| w == *p)
    });
    if !has_pronoun {
        return false;
    }

    // Check that there's no proper noun (capitalized word that isn't sentence-start)
    let words: Vec<&str> = query.split_whitespace().collect();
    let has_named_entity = words.iter().skip(1).any(|w| {
        w.chars().next().map(|c| c.is_uppercase()).unwrap_or(false)
            && !["I", "I'm", "I'd", "I've", "I'll"].contains(w)
    });

    !has_named_entity
}

/// Expand a pronoun-heavy query using the last known tool topic.
///
/// "how old is he?" + last_topic="John Cena" → "how old is John Cena?"
/// Replaces the first pronoun occurrence with the topic.
fn expand_with_topic(query: &str, topic: &str) -> String {
    let lower = query.to_lowercase();
    let pronouns = [
        ("he", topic),
        ("she", topic),
        ("they", topic),
        ("him", topic),
        ("her", topic),
        ("them", topic),
        ("his", &format!("{}'s", topic)),
        ("hers", &format!("{}'s", topic)),
        ("their", &format!("{}'s", topic)),
        ("it", topic),
        ("its", &format!("{}'s", topic)),
    ];

    for (pronoun, replacement) in &pronouns {
        // Find the pronoun as a whole word and replace the first occurrence
        let words: Vec<&str> = query.split_whitespace().collect();
        let idx = words.iter().position(|w| {
            w.trim_matches(|c: char| !c.is_alphanumeric())
                .to_lowercase()
                == *pronoun
        });
        if let Some(i) = idx {
            let mut result: Vec<String> = words.iter().map(|w| w.to_string()).collect();
            // Preserve punctuation around the word
            let original = words[i];
            let prefix: String = original
                .chars()
                .take_while(|c| !c.is_alphanumeric())
                .collect();
            let suffix: String = original
                .chars()
                .rev()
                .take_while(|c| !c.is_alphanumeric())
                .collect::<String>()
                .chars()
                .rev()
                .collect();
            result[i] = format!("{}{}{}", prefix, replacement, suffix);
            return result.join(" ");
        }
    }

    // No pronoun found to replace — prepend topic for context
    format!("{} — {}", topic, query)
}

/// Update the last tool topic after a successful lookup.
async fn set_last_tool_topic(topic: &str) {
    if let Some(handles) = GIAP_SERVICES.get() {
        *handles.last_tool_topic.write().await = topic.to_string();
    }
}

/// Tool Agent entry point: look up a topic on Wikipedia.
///
/// Called by the route handler BEFORE the main LLM runs. Uses the same
/// HTTP helpers as the MCP tool but bypasses the Goose agentic loop entirely.
/// Returns `Some(article_text)` on success, `None` if the lookup fails.
pub async fn try_wikipedia_lookup(query: &str) -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let server = GiapMcpServer::new(services.clone());
    let cleaned = crate::giap_server::clean_query_for_search(query);
    let mut topic = if cleaned.is_empty() {
        query.trim().to_string()
    } else {
        cleaned
    };
    if topic.is_empty() {
        return None;
    }

    // ── Coreference resolution: expand pronoun-heavy queries ──────────
    // "how old is he?" + last_topic="John Cena" → "how old is John Cena"
    if is_pronoun_query(query) {
        let last_topic = services.last_tool_topic.read().await;
        if !last_topic.is_empty() {
            let expanded = expand_with_topic(query, &last_topic);
            let expanded_clean = crate::giap_server::clean_query_for_search(&expanded);
            println!(
                "[tool-agent] pronoun query {:?} expanded to {:?} (last topic: {:?})",
                query, expanded_clean, *last_topic
            );
            topic = if expanded_clean.is_empty() {
                expanded
            } else {
                expanded_clean
            };
        }
    }

    println!("[tool-agent] wikipedia lookup for {:?}", topic);

    // Try direct title first, then search fallback
    match server.fetch_article_summary(&topic).await {
        Ok(text) => {
            println!("[tool-agent] direct hit for {:?}", topic);
            set_last_tool_topic(&topic).await;
            Some(text)
        }
        Err(crate::giap_server::WikiFetchError::NotFound) => {
            println!("[tool-agent] not found, searching for {:?}", topic);
            match server.search_and_fetch_best(&topic).await {
                Ok(text) => {
                    set_last_tool_topic(&topic).await;
                    Some(text)
                }
                Err(_) => None,
            }
        }
        Err(_) => None,
    }
}

/// Tool Agent entry point: get current weather.
pub async fn try_weather_lookup() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let weather = services.weather.as_ref()?;
    match weather.current().await {
        Ok(data) => {
            println!("[tool-agent] weather fetched successfully");
            Some(data.as_context_block())
        }
        Err(e) => {
            println!("[tool-agent] weather fetch failed: {e}");
            None
        }
    }
}

/// Unified Tool Agent: execute a specific tool by name.
/// Called after the classifier decides which tool is needed.
/// Returns `Some(result_text)` on success.
pub async fn try_tool_agent(tool: &str, message: &str) -> Option<String> {
    println!(
        "[tool-agent] executing tool={:?} for message={:?}",
        tool, message
    );
    match tool {
        "weather" => try_weather_lookup().await,
        "save_memory" => try_save_memory(message).await,
        "recall_memory" => try_recall_memory(message).await,
        "devices" => try_list_devices().await,
        "schedules" => try_list_schedules().await,
        "create_schedule" => try_create_schedule(message).await,
        "wikipedia" | _ => try_wikipedia_lookup(message).await,
    }
}

/// Save a memory fragment from the user's message, with auto-segment classification.
async fn try_save_memory(message: &str) -> Option<String> {
    use crate::giap_server::auto_classify_segment;
    use pond_core::domain::memory::{MemoryFragment, MemoryLifecycle};

    let services = GIAP_SERVICES.get()?;
    let cleaned = crate::giap_server::clean_query_for_search(message);
    let content = if cleaned.is_empty() {
        message.trim().to_string()
    } else {
        cleaned
    };

    let segment = auto_classify_segment(&content);
    let importance = segment.default_importance();
    let tier = segment.default_tier();
    let decay_rate = tier.default_decay_rate();

    let fragment = MemoryFragment {
        id: uuid::Uuid::new_v4().to_string(),
        profile_id: None,
        session_id: None,
        content: content.clone(),
        embedding: None,
        source: "tool_agent".to_string(),
        tags: vec![],
        created_at: chrono::Utc::now(),
        segment: Some(segment),
        importance: Some(importance),
        tier: Some(tier),
        decay_rate: Some(decay_rate),
        access_count: 0,
        last_accessed_at: None,
        lifecycle: Some(MemoryLifecycle::Active),
        superseded_by: None,
    };
    match services.memory_repo.add(fragment).await {
        Ok(_) => {
            println!("[tool-agent] memory saved: {:?}", content);
            Some(format!("Memory saved: {}", content))
        }
        Err(e) => {
            println!("[tool-agent] memory save failed: {e}");
            None
        }
    }
}

/// Recall recent memories, optionally filtered by the user's query.
async fn try_recall_memory(message: &str) -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let memories = services.memory_repo.search_recent(None, 10).await.ok()?;
    if memories.is_empty() {
        return Some("No saved memories found.".to_string());
    }
    let cleaned = crate::giap_server::clean_query_for_search(message).to_lowercase();
    let filtered: Vec<_> = if cleaned.is_empty() {
        memories
    } else {
        memories
            .into_iter()
            .filter(|m| m.content.to_lowercase().contains(&cleaned))
            .collect()
    };
    if filtered.is_empty() {
        return Some(format!("No memories found matching '{}'.", cleaned));
    }
    let text = filtered
        .iter()
        .map(|m| format!("- [{}] {}", m.created_at.format("%Y-%m-%d"), m.content))
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] recalled {} memories", filtered.len());
    Some(text)
}

/// List registered devices.
async fn try_list_devices() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let devices = services.device_registry.list_devices().await.ok()?;
    if devices.is_empty() {
        return Some("No devices registered.".to_string());
    }
    let text = devices
        .iter()
        .map(|d| {
            format!(
                "- {} ({}): {}",
                d.name,
                d.device_type,
                if d.is_online { "online" } else { "offline" }
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] listed {} devices", devices.len());
    Some(text)
}

/// List scheduled tasks with kind and timezone info.
async fn try_list_schedules() -> Option<String> {
    use pond_core::domain::schedule::TaskKind;
    let services = GIAP_SERVICES.get()?;
    let scheduler = services.scheduler.as_ref()?;
    let tasks = scheduler.list_tasks().await.ok()?;
    if tasks.is_empty() {
        return Some("No scheduled tasks.".to_string());
    }
    let text = tasks
        .iter()
        .map(|t| {
            let kind_label = match &t.kind {
                TaskKind::AgentPrompt { .. } => "agent",
                TaskKind::Webhook { .. } => "webhook",
            };
            let status = if t.currently_running {
                "running"
            } else if t.paused {
                "paused"
            } else {
                "active"
            };
            format!(
                "- {} [{}]: {} {} ({}, {})",
                t.label, t.id, t.cron, t.timezone, kind_label, status
            )
        })
        .collect::<Vec<_>>()
        .join("\n");
    println!("[tool-agent] listed {} schedules", tasks.len());
    Some(text)
}

/// Create a schedule from a natural language message.
///
/// Parses common time patterns (e.g. "at 10 am every morning", "every day at 8",
/// "every hour") into a 6-field cron expression and creates the schedule.
/// Returns a confirmation message on success.
async fn try_create_schedule(message: &str) -> Option<String> {
    use pond_core::domain::schedule::TaskKind;
    use pond_core::ports::scheduler::CreateScheduleRequest;

    let services = GIAP_SERVICES.get()?;
    let scheduler = services.scheduler.as_ref()?;

    let lower = message.to_lowercase();

    // ── Parse time from message ──────────────────────────────────────────
    let cron = parse_cron_from_message(&lower)?;

    // ── Extract the action/prompt ────────────────────────────────────────
    // Strip scheduling prefixes to get what the user actually wants done.
    let prompt = extract_prompt_from_message(&lower, message);

    // Get user timezone from settings.
    let timezone = services
        .settings_repo
        .get()
        .await
        .map(|s| s.timezone.clone())
        .unwrap_or_else(|_| "UTC".to_string());

    let id = uuid::Uuid::new_v4().to_string();
    let label = if prompt.len() > 40 {
        format!("{}...", &prompt[..37])
    } else {
        prompt.clone()
    };

    let req = CreateScheduleRequest {
        id: id.clone(),
        label,
        cron: cron.clone(),
        timezone: timezone.clone(),
        kind: TaskKind::AgentPrompt {
            prompt: prompt.clone(),
        },
    };

    match scheduler.create_task(req).await {
        Ok(schedule) => {
            println!(
                "[tool-agent] created schedule: {} [{}] cron={} tz={}",
                schedule.label, schedule.id, schedule.cron, schedule.timezone
            );
            Some(format!(
                "Schedule created successfully!\n\
                 - Name: {}\n\
                 - Schedule: {} ({})\n\
                 - Prompt: \"{}\"\n\
                 - ID: {}\n\n\
                 The agent will automatically run this prompt at the scheduled time.",
                schedule.label, schedule.cron, schedule.timezone, prompt, schedule.id,
            ))
        }
        Err(e) => {
            println!("[tool-agent] create_schedule failed: {e}");
            Some(format!("Failed to create schedule: {e}"))
        }
    }
}

/// Parse a 6-field cron expression from a natural language time description.
/// Returns `None` if no recognizable time pattern is found.
fn parse_cron_from_message(lower: &str) -> Option<String> {
    // Try to extract "at HH" or "at HH:MM" patterns
    let hour = extract_hour(lower);

    if lower.contains("every minute") {
        return Some("0 * * * * *".to_string());
    }
    if lower.contains("every hour") || lower.contains("hourly") {
        let min = extract_minute(lower).unwrap_or(0);
        return Some(format!("0 {min} * * * *"));
    }

    // "every morning" / "every day" / "daily"
    if lower.contains("every morning")
        || lower.contains("every day")
        || lower.contains("daily")
        || lower.contains("each morning")
        || lower.contains("each day")
    {
        let h = hour.unwrap_or(8); // default 8 AM for "every morning"
        let m = extract_minute(lower).unwrap_or(0);
        return Some(format!("0 {m} {h} * * *"));
    }

    // "every evening" / "every night"
    if lower.contains("every evening") || lower.contains("every night") {
        let h = hour.unwrap_or(20); // default 8 PM
        let m = extract_minute(lower).unwrap_or(0);
        return Some(format!("0 {m} {h} * * *"));
    }

    // "every week" / "weekly" / "every monday" etc.
    if lower.contains("every week") || lower.contains("weekly") {
        let h = hour.unwrap_or(8);
        let m = extract_minute(lower).unwrap_or(0);
        let dow = extract_day_of_week(lower).unwrap_or(1); // default Monday
        return Some(format!("0 {m} {h} * * {dow}"));
    }

    // Bare "at X am/pm" without frequency → default to daily
    if let Some(h) = hour {
        let m = extract_minute(lower).unwrap_or(0);
        return Some(format!("0 {m} {h} * * *"));
    }

    None
}

/// Extract hour from patterns like "at 10 am", "at 8pm", "at 14:30"
fn extract_hour(s: &str) -> Option<u32> {
    // Pattern: "at HH" or "at H"
    let patterns = ["at ", "by "];
    for pat in patterns {
        if let Some(idx) = s.find(pat) {
            let after = &s[idx + pat.len()..];
            let num_str: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
            if let Ok(mut h) = num_str.parse::<u32>() {
                let rest = after[num_str.len()..].trim_start();
                if rest.starts_with("pm") || rest.starts_with("p.m") {
                    if h < 12 {
                        h += 12;
                    }
                } else if rest.starts_with("am") || rest.starts_with("a.m") {
                    if h == 12 {
                        h = 0;
                    }
                }
                if h <= 23 {
                    return Some(h);
                }
            }
        }
    }
    // Pattern: "N o'clock"
    if let Some(idx) = s.find("o'clock").or_else(|| s.find("o clock")) {
        let before = s[..idx].trim_end();
        let num_str: String = before
            .chars()
            .rev()
            .take_while(|c| c.is_ascii_digit())
            .collect::<String>()
            .chars()
            .rev()
            .collect();
        if let Ok(h) = num_str.parse::<u32>() {
            if h <= 23 {
                return Some(h);
            }
        }
    }
    None
}

/// Extract minute from "HH:MM" or ":MM"
fn extract_minute(s: &str) -> Option<u32> {
    // Look for :MM pattern after a digit
    for (i, _) in s.match_indices(':') {
        if i > 0 && s.as_bytes()[i - 1].is_ascii_digit() {
            let after = &s[i + 1..];
            let num_str: String = after
                .chars()
                .take(2)
                .take_while(|c| c.is_ascii_digit())
                .collect();
            if let Ok(m) = num_str.parse::<u32>() {
                if m < 60 {
                    return Some(m);
                }
            }
        }
    }
    None
}

/// Extract day of week (0=Sun, 1=Mon, ... 6=Sat) for tokio-cron-scheduler.
fn extract_day_of_week(s: &str) -> Option<u32> {
    if s.contains("sunday") || s.contains("sun") {
        return Some(0);
    }
    if s.contains("monday") || s.contains("mon") {
        return Some(1);
    }
    if s.contains("tuesday") || s.contains("tue") {
        return Some(2);
    }
    if s.contains("wednesday") || s.contains("wed") {
        return Some(3);
    }
    if s.contains("thursday") || s.contains("thu") {
        return Some(4);
    }
    if s.contains("friday") || s.contains("fri") {
        return Some(5);
    }
    if s.contains("saturday") || s.contains("sat") {
        return Some(6);
    }
    None
}

/// Extract the action prompt from a scheduling message.
/// Strips scheduling-related prefixes to get the core task description.
fn extract_prompt_from_message(lower: &str, original: &str) -> String {
    // Common prefixes to strip
    let strip_patterns = [
        "schedule to ",
        "schedule ",
        "set up a ",
        "set up ",
        "every morning ",
        "every day ",
        "every evening ",
        "every night ",
        "every hour ",
        "every week ",
        "every minute ",
        "daily ",
        "hourly ",
        "weekly ",
        "remind me to ",
        "remind me ",
        "at ",
        "by ",
    ];

    let mut work = lower.to_string();

    // Strip leading scheduling/time words
    for pat in &strip_patterns {
        if let Some(rest) = work.strip_prefix(pat) {
            work = rest.to_string();
        }
    }

    // Strip "at HH am/pm" and "every X" from middle
    let time_re_patterns = [
        "at ",
        "every morning",
        "every day",
        "every evening",
        "every night",
        "every hour",
        "every week",
        "every minute",
        "daily",
        "hourly",
        "weekly",
    ];
    for pat in &time_re_patterns {
        work = work.replace(pat, " ");
    }

    // Strip am/pm and digits that look like times
    let cleaned: String = work
        .split_whitespace()
        .filter(|w| {
            !w.chars().all(|c| c.is_ascii_digit() || c == ':')
                && *w != "am"
                && *w != "pm"
                && *w != "a.m."
                && *w != "p.m."
        })
        .collect::<Vec<_>>()
        .join(" ");

    let trimmed = cleaned.trim().to_string();

    // If extraction left nothing useful, use the original message as the prompt
    if trimmed.len() < 5 {
        return original.trim().to_string();
    }

    // Capitalize first letter
    let mut chars = trimmed.chars();
    match chars.next() {
        Some(c) => format!("{}{}", c.to_uppercase(), chars.collect::<String>()),
        None => original.trim().to_string(),
    }
}

/// Build a context block of upcoming scheduled tasks for system prompt injection.
/// Returns `Some("## Upcoming Scheduled Tasks\n- ...")` or `None` if no active tasks.
pub async fn try_upcoming_schedules_context() -> Option<String> {
    let services = GIAP_SERVICES.get()?;
    let scheduler = services.scheduler.as_ref()?;
    let tasks = scheduler.list_upcoming(5).await.ok()?;
    if tasks.is_empty() {
        return None;
    }
    let lines: Vec<String> = tasks
        .iter()
        .map(|t| {
            let kind_label = match &t.kind {
                pond_core::domain::schedule::TaskKind::AgentPrompt { prompt } => {
                    let preview = if prompt.len() > 60 {
                        format!("{}...", &prompt[..57])
                    } else {
                        prompt.clone()
                    };
                    format!("agent: \"{preview}\"")
                }
                pond_core::domain::schedule::TaskKind::Webhook { webhook_url } => {
                    format!("webhook: {webhook_url}")
                }
            };
            format!(
                "- \"{}\" — {} {} ({})",
                t.label, t.cron, t.timezone, kind_label
            )
        })
        .collect();
    Some(format!("## Upcoming Scheduled Tasks\n{}", lines.join("\n")))
}

pub fn spawn_giap_server(reader: DuplexStream, writer: DuplexStream) {
    let services = GIAP_SERVICES
        .get()
        .expect("GIAP services not initialized — call init_giap_services() first")
        .clone();
    let server = GiapMcpServer::new(services);
    tokio::spawn(async move {
        match server.serve((reader, writer)).await {
            Ok(running) => {
                let _ = running.waiting().await;
            }
            Err(e) => {
                tracing::error!("GIAP MCP server failed to start: {e}");
            }
        }
    });
}
