//! Per-turn telemetry metrics for the agent pipeline.
//!
//! Each chat turn produces a `TurnMetrics` snapshot capturing token usage,
//! latency breakdown, tool execution details, and context window utilization.
//! These metrics enable measurement and optimization of the inference loop,
//! especially on memory-constrained devices like the Jetson Orin Nano.

use serde::{Deserialize, Serialize};

/// Snapshot of a single chat turn's performance characteristics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TurnMetrics {
    /// Session this turn belongs to.
    pub session_id: String,
    /// 1-based turn index within the session.
    pub turn_number: u32,
    /// Tokens consumed by the prompt (input).
    pub prompt_tokens: u32,
    /// Tokens generated by the model (output).
    pub completion_tokens: u32,
    /// Time to first token in milliseconds (measures model load + prefill latency).
    pub ttft_ms: u64,
    /// Total wall-clock time for the turn in milliseconds.
    pub total_latency_ms: u64,
    /// Name of the tool executed during this turn, if any.
    pub tool_name: Option<String>,
    /// Wall-clock time for tool execution in milliseconds.
    pub tool_latency_ms: Option<u64>,
    /// Whether the tool result came from cache.
    pub tool_cache_hit: Option<bool>,
    /// Estimated percentage of the model's context window consumed (0.0–100.0).
    pub context_utilization_pct: f32,
    /// Model identifier used for this turn.
    pub model_name: String,
    /// ISO 8601 timestamp when the turn completed.
    pub timestamp: String,
    /// Prefill time (template + tokenize + prompt decode), summed across the
    /// turn's inferences. Engine-reported; None for providers without stats.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefill_ms: Option<u64>,
    /// Cold model-load time when a load happened during this turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_load_ms: Option<u64>,
    /// Generation speed in tokens/second (decode phase).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub decode_tok_per_sec: Option<f32>,
    /// Prompt-processing speed in tokens/second (prefill phase).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prefill_tok_per_sec: Option<f32>,
    /// Engine-reported context window (n_ctx) for this turn.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_limit_tokens: Option<u32>,
    /// Number of inferences the agentic loop ran (1 + tool round-trips).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inference_count: Option<u32>,
}

/// Aggregated telemetry summary for a session.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TelemetrySummary {
    /// Average time to first token across all turns (milliseconds).
    pub avg_ttft_ms: f64,
    /// Average completion tokens per turn.
    pub avg_completion_tokens: f64,
    /// Total number of turns recorded.
    pub total_turns: u32,
    /// Average context window utilization across all turns (percentage).
    pub avg_context_utilization: f64,
}
