pub mod acceleration;
pub mod curated;
pub mod device_budget;
pub mod device_profile;
pub mod engine;
pub mod gguf;
pub mod image_limits;
pub mod litert;
pub mod message;
pub mod mic_gate;
pub mod model_capabilities;
pub mod model_layout;
pub mod model_probe;
pub mod model_record; // re-exports ModelRecord, ModelCategory, ModelRoleAssignment, BinaryRecord
pub mod model_role;
pub mod recommended;
pub mod taxonomy;
pub mod vision_encoder;
pub mod vision_pairing;
